
server:
  port: 9000

spring:
  application:  # 指定微服务对外暴露的名称
    name: 09-consumer-turbine-monitor-9000

eureka:
  client:
    service-url: # 指定Eureka服务注册中心
      defaultZone: http://localhost:8000/eureka

# 开启Feign对Hystrix的支持
feign:
  hystrix:
    enabled: true

  client:
    config:
      default:
        connectTimeout: 5000  # 指定Feign连接提供者的超时时限
        readTimeout: 5000    # 指定Feign从请求到获取提供者响应的超时时限

# 开启actuator的所有web终端
management:
  endpoints:
    web:
      exposure:
        include: "*"

# 设置服务熔断时限
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
turbine:
  app-config: abcmsc-consumer-depart01,abcmsc-consumer-depart02
  cluster-name-expression: new String("default")
  combine-host-port: true
  instanceUrlSuffix: /actuator/hystrix.stream #turbine默认监控actuator/路径下的端点，修改直接监控hystrix.stream
    #cluster-name-expression: metadata['cluster']
    #aggregator:
  # cluster-config: ribbon
  #instanceUrlSuffix:  /hystrix.stream #turbine默认监控actuator/路径下的端点，修改直接监控hystrix.stream
